In [3]:
import numpy as np

# The Basics of NumPy Arrays

Data manipulation in Python is nearly synonymous with NumPy array manipulation: even newer tools like Pandas  are built around the NumPy array.
This section will present several examples of using NumPy array manipulation to access data and subarrays, and to split, reshape, and join the arrays.

We'll cover a few categories of basic array manipulations here:

- *Attributes of arrays*: Determining the size, shape, memory consumption, and data types of arrays
- *Indexing of arrays*: Getting and setting the value of individual array elements
- *Slicing of arrays*: Getting and setting smaller subarrays within a larger array
- *Reshaping of arrays*: Changing the shape of a given array
- *Joining and splitting of arrays*: Combining multiple arrays into one, and splitting one array into many

## NumPy Array Attributes

First let's discuss some useful array attributes.
We'll start by defining three random arrays, a one-dimensional, two-dimensional, and three-dimensional array.
We'll use NumPy's random number generator, which we will *seed* with a set value in order to ensure that the same random arrays are generated each time this code is run:

In [13]:
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 3))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array
print(x1)
print(x2)
print(x3)

[5 0 3 3 7 9]
[[3 5 2]
 [4 7 6]
 [8 8 1]]
[[[6 7 7 8 1]
  [5 9 8 9 4]
  [3 0 3 5 0]
  [2 3 8 1 3]]

 [[3 3 7 0 1]
  [9 9 0 4 7]
  [3 2 7 2 0]
  [0 4 5 5 6]]

 [[8 4 1 4 9]
  [8 1 1 7 9]
  [9 3 6 7 2]
  [0 3 5 9 4]]]


In [27]:
c=np.zeros((3,4))
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.random.randint(0,10, (3,4))

array([[4, 6, 4, 4],
       [3, 4, 4, 8],
       [4, 3, 7, 5]])

Each array has attributes ``ndim`` (the number of dimensions), ``shape`` (the size of each dimension), and ``size`` (the total size of the array):

In [21]:
print(x1.ndim)
print(x1.shape)
print(x1.size)

1
(6,)
6


In [22]:
# print(x1)
# print(x2)
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


Another useful attribute is the ``dtype``, the data type of the array.

In [29]:
print("dtype:", x3.dtype)

dtype: int64


Other attributes include ``itemsize``, which lists the size (in bytes) of each array element, and ``nbytes``, which lists the total size (in bytes) of the array:

In [32]:
print("itemsize:", x3.itemsize, "bytes") # per item size
print("Total Array size: ", x3.size)
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
Total Array size:  60
nbytes: 480 bytes


In general, we expect that ``nbytes`` is equal to ``itemsize`` times ``size``.

``nbytes = itemsize * size ``

## Array Indexing: Accessing Single Elements

If you are familiar with Python's standard list indexing, indexing in NumPy will feel quite familiar.
In a one-dimensional array, the $i^{th}$ value (counting from zero) can be accessed by specifying the desired index in square brackets, just as with Python lists:

In [33]:
x1

array([5, 0, 3, 3, 7, 9])

In [34]:
x1[0]

5

In [35]:
x1[4]

7

To index from the end of the array, you can use negative indices:

In [36]:
x1[-1]

9

In [37]:
x1[-2]

7

In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:

In [38]:
x2

array([[3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [39]:
x2[0]

array([3, 5, 2])

In [40]:
x2[(2, 0)]

8

In [43]:
x2[2][0]

8

In [42]:
x2[-2, -3]

4

Values can also be modified using any of the above index notation:

In [46]:
x2[0, 0] = 12
x2

array([[12,  5,  2],
       [ 4,  7,  6],
       [ 8,  8,  1]])

Keep in mind that, unlike Python lists, NumPy arrays have a fixed type.
This means, for example, that if you attempt to insert a floating-point value to an integer array, the value will be silently truncated. Don't be caught unaware by this behavior!

In [47]:
x2.dtype

dtype('int64')

In [48]:
x2[2,1] = 9.14159  # this will be truncated!
x2

array([[12,  5,  2],
       [ 4,  7,  6],
       [ 8,  9,  1]])

### Indexing Format for n-dim array

```
arr[block, row, column]
```

In [49]:
x3

array([[[6, 7, 7, 8, 1],
        [5, 9, 8, 9, 4],
        [3, 0, 3, 5, 0],
        [2, 3, 8, 1, 3]],

       [[3, 3, 7, 0, 1],
        [9, 9, 0, 4, 7],
        [3, 2, 7, 2, 0],
        [0, 4, 5, 5, 6]],

       [[8, 4, 1, 4, 9],
        [8, 1, 1, 7, 9],
        [9, 3, 6, 7, 2],
        [0, 3, 5, 9, 4]]])

In [50]:
x3[2]

array([[8, 4, 1, 4, 9],
       [8, 1, 1, 7, 9],
       [9, 3, 6, 7, 2],
       [0, 3, 5, 9, 4]])

In [51]:
x3[0, 2, 3] 

5

## Array Slicing: Accessing Subarrays

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the *slice* notation, marked by the colon (``:``) character.
The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array ``x``, use this:
``` python
x[start:stop:step]
```
If any of these are unspecified, they default to the values ``start=0``, ``stop=``*``size of dimension``*, ``step=1``.
We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

### One-dimensional subarrays

In [52]:
x1

array([5, 0, 3, 3, 7, 9])

In [53]:
x1[:5]  # first five elements

array([5, 0, 3, 3, 7])

In [54]:
x1[5:]  # elements after index 5

array([9])

In [59]:
x1[4:9]  # middle sub-array

array([7, 9])

In [60]:
x1[::2]  # every other element

array([5, 3, 7])

In [61]:
x1[1::2]  # every other element, starting at index 1

array([0, 3, 9])

A potentially confusing case is when the ``step`` value is negative.
In this case, the defaults for ``start`` and ``stop`` are swapped.
This becomes a convenient way to reverse an array:

In [64]:
x1

array([5, 0, 3, 3, 7, 9])

In [62]:
x1[::-1]  # all elements, reversed

array([9, 7, 3, 3, 0, 5])

In [63]:
x1[3::-1]  # reversed every other from index 3

array([3, 3, 0, 5])

### Multi-dimensional subarrays

Multi-dimensional slices work in the same way, with multiple slices separated by commas.

``[start_row_index:end_row_index, start_column_index:end_column_index]``

Recall that the index structure for both the row and column range is inclusive of the first index, but not the second index.



In [65]:
x2

array([[12,  5,  2],
       [ 4,  7,  6],
       [ 8,  9,  1]])

In [66]:
x2[0,2]

2

In [67]:
x2[0:2, 1:2]

array([[5],
       [7]])

In [68]:
x2[0:2]

array([[12,  5,  2],
       [ 4,  7,  6]])

In [69]:
x2[:2, :3]  # two rows, three columns

array([[12,  5,  2],
       [ 4,  7,  6]])

In [70]:
x2[:3, ::2]  # all rows, every other column

array([[12,  2],
       [ 4,  6],
       [ 8,  1]])

Finally, subarray dimensions can even be reversed together:

In [71]:
x2

array([[12,  5,  2],
       [ 4,  7,  6],
       [ 8,  9,  1]])

In [72]:
x2[::-1, ::-1]

array([[ 1,  9,  8],
       [ 6,  7,  4],
       [ 2,  5, 12]])

In [73]:
x2[::-1]

array([[ 8,  9,  1],
       [ 4,  7,  6],
       [12,  5,  2]])

In [74]:
x2[::, ::-1]

array([[ 2,  5, 12],
       [ 6,  7,  4],
       [ 1,  9,  8]])

### slicing on an N-dimensional NumPy array

```
(block, rows, cols)
```

In [75]:
x3

array([[[6, 7, 7, 8, 1],
        [5, 9, 8, 9, 4],
        [3, 0, 3, 5, 0],
        [2, 3, 8, 1, 3]],

       [[3, 3, 7, 0, 1],
        [9, 9, 0, 4, 7],
        [3, 2, 7, 2, 0],
        [0, 4, 5, 5, 6]],

       [[8, 4, 1, 4, 9],
        [8, 1, 1, 7, 9],
        [9, 3, 6, 7, 2],
        [0, 3, 5, 9, 4]]])

In [76]:
#Select first block
x3[0]

array([[6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4],
       [3, 0, 3, 5, 0],
       [2, 3, 8, 1, 3]])

In [77]:
# Select first row of first block
x3[0, 0]

array([6, 7, 7, 8, 1])

In [78]:
#Select first column across all blocks
x3[:, :, 0]

array([[6, 5, 3, 2],
       [3, 9, 3, 0],
       [8, 8, 9, 0]])

In [82]:
x3

array([[[6, 7, 7, 8, 1],
        [5, 9, 8, 9, 4],
        [3, 0, 3, 5, 0],
        [2, 3, 8, 1, 3]],

       [[3, 3, 7, 0, 1],
        [9, 9, 0, 4, 7],
        [3, 2, 7, 2, 0],
        [0, 4, 5, 5, 6]],

       [[8, 4, 1, 4, 9],
        [8, 1, 1, 7, 9],
        [9, 3, 6, 7, 2],
        [0, 3, 5, 9, 4]]])

In [79]:
#Every second element in each dimension
x3[:, ::2, ::2]

array([[[6, 7, 1],
        [3, 3, 0]],

       [[3, 7, 1],
        [3, 7, 0]],

       [[8, 1, 9],
        [9, 6, 2]]])

In [83]:
#Middle rows from all blocks
x3[:, 1:3, :]

array([[[5, 9, 8, 9, 4],
        [3, 0, 3, 5, 0]],

       [[9, 9, 0, 4, 7],
        [3, 2, 7, 2, 0]],

       [[8, 1, 1, 7, 9],
        [9, 3, 6, 7, 2]]])

#### Accessing array rows and columns

One commonly needed routine is accessing of single rows or columns of an array.
This can be done by combining indexing and slicing, using an empty slice marked by a single colon (``:``):

In [84]:
x2

array([[12,  5,  2],
       [ 4,  7,  6],
       [ 8,  9,  1]])

In [85]:
print(x2[:, 0])  # first column of x2

[12  4  8]


In [86]:
print(x2[0, :])  # first row of x2

[12  5  2]


In the case of row access, the empty slice can be omitted for a more compact syntax:

In [87]:
print(x2[0])  # equivalent to x2[0, :]

[12  5  2]


### Subarrays as no-copy views

One important–and extremely useful–thing to know about array slices is that they return *views* rather than *copies* of the array data.
This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies.
Consider our two-dimensional array from before:

In [88]:
print(x2)

[[12  5  2]
 [ 4  7  6]
 [ 8  9  1]]


Let's extract a $2 \times 2$ subarray from this:

In [89]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 4  7]]


Now if we modify this subarray, we'll see that the original array is changed! Observe:

In [90]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 4  7]]


In [91]:
print(x2)

[[99  5  2]
 [ 4  7  6]
 [ 8  9  1]]


This default behavior is actually quite useful: it means that when we work with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer.

### Creating copies of arrays

Despite the nice features of array views, it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be most easily done with the ``copy()`` method:

In [92]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 4  7]]


If we now modify this subarray, the original array is not touched:

In [93]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 4  7]]


In [94]:
print(x2)

[[99  5  2]
 [ 4  7  6]
 [ 8  9  1]]


## Reshaping of Arrays

Another useful type of operation is reshaping of arrays.
The most flexible way of doing this is with the ``reshape`` method.
For example, if you want to put the numbers 1 through 9 in a $3 \times 3$ grid, you can do the following:

In [97]:
# import numpy as np
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Note that for this to work, the size of the initial array must match the size of the reshaped array. 
Where possible, the ``reshape`` method will use a no-copy view of the initial array, but with non-contiguous memory buffers this is not always the case.

Another common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix.
This can be done with the ``reshape`` method, or more easily done by making use of the ``newaxis`` keyword within a slice operation:

In [101]:
x = np.array([1, 2, 3])
print(x.shape)
# row vector via reshape
a = x.reshape((1, 3))
a.shape

(3,)


(1, 3)

In [102]:
# row vector via newaxis
a = x[np.newaxis, :]
a.shape

(1, 3)

In [103]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [104]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

### np.newaxis?
```
It is just a way to add a new axis (dimension) to an array.
Technically, it’s the same as using None in slicing.
```

In [105]:
arr = np.array([1, 2, 3, 4])
print("Original shape:", arr.shape)   # (4,)

# Convert to column vector
col = arr[:, np.newaxis]
print("Column shape:", col.shape)     # (4, 1)

# Convert to row vector
row = arr[np.newaxis, :]
print("Row shape:", row.shape)        # (1, 4)


Original shape: (4,)
Column shape: (4, 1)
Row shape: (1, 4)


In [106]:
print(arr[:, None].shape)       # (4, 1)
print(arr[:, np.newaxis].shape) # (4, 1)  ✅ same

(4, 1)
(4, 1)
