In [1]:
import numpy as np

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


## Array Concatenation and Splitting

All of the preceding routines worked on single arrays. It's also possible to combine multiple arrays into one, and to conversely split a single array into multiple arrays. We'll take a look at those operations here.

### Concatenation of arrays

Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routines ``np.concatenate``, ``np.vstack``, and ``np.hstack``.
``np.concatenate`` takes a tuple or list of arrays as its first argument, as we can see here:

``axis=0 → across rows, down the vertical direction.
axis=1 → across columns, horizontal direction.``

In [2]:
x = np.array([1, 2, 3])
y = np.array((3, 2, 1))
print(x.shape, y.shape, np.concatenate([x, y],  axis = 0))

(3,) (3,) [1 2 3 3 2 1]


``Because x and y are both 1D arrays of shape (3,). Concatenation happens along that single axis.``

#### If i try to reshape it and make concatenation, it creates Axiserror

In [5]:
x.reshape(1,3)
y.reshape(1,3)
print(x.shape, y.shape)
np.concatenate([x, y], axis = 1)

(3,) (3,)


AxisError: axis 1 is out of bounds for array of dimension 1

```
x.reshape(1,3) → creates a reshaped view of x, but you didn’t assign it back.
x is still shape (3,), not (1,3).
Similarly, y.reshape(1,3) → but y remains shape (3,).
```

In [6]:
x = x.reshape(1,3)
y = y.reshape(1,3)
np.concatenate([x, y])

array([[1, 2, 3],
       [3, 2, 1]])

```
concatenate → works on existing axes only.
stack / vstack → create a new axis (row-wise stacking).
```

In [7]:
x.shape

(1, 3)

In [8]:
x2 = np.arange(1, 10).reshape((3, 3))
x2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.concatenate([x, x2], axis = 0)

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

You can also concatenate more than two arrays at once:

In [10]:
z = np.array([99, 99, 99]).reshape(1,3)
print(np.concatenate([x,y,x2,z]))

[[ 1  2  3]
 [ 3  2  1]
 [ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [99 99 99]]


It can also be used for two-dimensional arrays:

In [11]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [12]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [13]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

For working with arrays of mixed dimensions, it can be clearer to use the ``np.vstack`` (vertical stack) and ``np.hstack`` (horizontal stack) functions:

In [14]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays

print(x.shape, grid.shape)
np.vstack([x, grid])

(3,) (2, 3)


array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [15]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])

print(y.shape, grid.shape)
np.hstack([grid, y])

(2, 1) (2, 3)


array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

### Splitting of arrays

The opposite of concatenation is splitting, which is implemented by the functions ``np.split``, ``np.hsplit``, and ``np.vsplit``.  For each of these, we can pass a list of indices giving the split points:

``numpy.split(ary, indices_or_sections, axis=0)``

In [16]:
x = [1, 2, 3, 99, 99, 3, 2, 1, 5]
x1, x2, x3 = np.split(x, [3,6], axis =0)
print(x1, x2, x3)

[1 2 3] [99 99  3] [2 1 5]


In [17]:
print(grid)

[[9 8 7]
 [6 5 4]]


In [20]:
x1, x2, x3 = np.split(grid, [1, 2], axis =1)
print(x1)
print(x2)
print(x3)

[[9]
 [6]]
[[8]
 [5]]
[[7]
 [4]]


Notice that *N* split-points, leads to *N + 1* subarrays.
The related functions ``np.hsplit`` and ``np.vsplit`` are similar:

In [21]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [22]:
upper, lower = np.vsplit(grid, [2])
print("Upper = " , upper)
print("Lower = " , lower)

Upper =  [[0 1 2 3]
 [4 5 6 7]]
Lower =  [[ 8  9 10 11]
 [12 13 14 15]]


In [23]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


# Write an Array to a CSV File in Python Using the numpy.savetxt() Method

The ``numpy.savetxt(fname, array, delimiter=)`` method saves the input array to the file ``- fname``. The ``delimiter`` argument is the value used as the separator to separate the independent value in the data.

To save the array to a CSV file, we will need to pass the ``fname`` with the ``.csv`` extension and use the comma ``,`` as the separator. The below example code demonstrates how to use the ``numpy.savetxt()`` to write an array to a CSV file in Python.``numpy.loadtxt()`` can be used to laod data into notebook.

In [24]:
# a = np.array([[1,4,2],[7,9,4],[0,6,2]])
np.savetxt('Array1.csv', grid, delimiter=',', fmt="%d")

In [25]:
arr = np.loadtxt("Array1.csv", delimiter=",", dtype = int)
print(arr)  #all numbers are read as floating-point values, 
                # unless you explicitly tell NumPy.

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [33]:
arr = np.loadtxt("Array1.csv", delimiter=",").astype(np.int64)
print(arr)

ValueError: the number of columns changed from 4 to 3 at row 5; use `usecols` to select a subset and avoid this error

# Write Array to a CSV File in Python Using the writer.writerows() Method 

In [28]:
import csv
import numpy

arr = numpy.array([[7,9,1],[5,6,3],[1,4,3]])

with open('Array1.csv', 'a') as file:
    mywriter = csv.writer(file, delimiter=',')
    mywriter.writerows(arr)

To read the array from the CSV file, we can use the ``csv.reader(file)`` method’s ``writer`` object to read the array from the ``file`` object file of the CSV file in Python.

In [31]:
import csv

with open('Array1.csv', 'r', newline='') as file:
      myreader = csv.reader(file, delimiter=',')
      for rows in myreader:
        print(rows)

['0', '1', '2', '3']
['4', '5', '6', '7']
['8', '9', '10', '11']
['12', '13', '14', '15']
['7', '9', '1']
['5', '6', '3']
['1', '4', '3']


``` 
csv.reader(f) → reads rows as lists of strings (["10", "20", "30"]).
map(int, row) → converts each element of the row to an integer.
```

In [32]:
import csv

with open('Array1.csv', 'r', newline='') as file:
    reader = csv.reader(file)
    
    # Convert each row (list of strings) → list of ints
    data = [list(map(int, row)) for row in reader]

# print(data)

    for i in data:
        print(i)

[0, 1, 2, 3]
[4, 5, 6, 7]
[8, 9, 10, 11]
[12, 13, 14, 15]
[7, 9, 1]
[5, 6, 3]
[1, 4, 3]
