# Fancy Indexing

In the previous sections, we saw how to access and modify portions of arrays using simple indices (e.g., ``arr[0]``), slices (e.g., ``arr[:5]``).
In this section, we'll look at another style of array indexing, known as *fancy indexing*.
Fancy indexing is like the simple indexing we've already seen, but we pass arrays of indices in place of single scalars.
This allows us to very quickly access and modify complicated subsets of an array's values.

## Exploring Fancy Indexing - Eg 1

Fancy indexing is conceptually simple: it means passing an array of indices to access multiple array elements at once.
For example, consider the following array:

In [2]:
import numpy as np

x = np.random.randint(100, size=10)
print(x)

[ 3 89 67  4 14 60  1 63 79 16]


Fancy indexing means using arrays/lists of indices (instead of just slices) to extract or modify elements of a NumPy array.


Suppose we want to access three different elements. We could do it like this:

In [3]:
[x[1], x[5], x[7]]

[89, 60, 63]

Alternatively, we can pass a single list or array of indices to obtain the same result:

In [5]:
ind = [1, 5, 7]
x[ind]

array([89, 60, 63])

## Eg 2

In [6]:
arr = np.arange(10, 20)   # array([10, 11, 12, ..., 19])
print(arr[[1, 3, 5]])     

[11 13 15]


### Basic indexing always creates views.

In [7]:
x = np.arange(10)
y = x[1:3]  # creates a view
print(x,y)

[0 1 2 3 4 5 6 7 8 9] [1 2]


In [8]:
x[1:3] = [10, 11]
print(x,y)

[ 0 10 11  3  4  5  6  7  8  9] [10 11]


Here, y gets changed when x is changed because it is a view.

### Fancy indexing on the other hand, always creates copies.

In [9]:
x = np.arange(9).reshape(3, 3)
y = x[[1, 2]]
print(x)
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [6 7 8]]


Here, y is a copy, as signified by the base attribute. We can also confirm this by assigning new values to x[[1, 2]] which in turn will not affect y at all:

In [10]:
x[[1, 2]] = [[10, 11, 12], [13, 14, 15]]
print(x)
print(y)

[[ 0  1  2]
 [10 11 12]
 [13 14 15]]
[[3 4 5]
 [6 7 8]]


### How to tell if the array is a view or a copy
The ``base`` attribute of the ndarray makes it easy to tell if an array is a view or a copy. The ``base`` attribute of a view returns the ``original array`` while it returns ``None`` for a copy.

In [11]:
x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
y = x.reshape(3, 3)
y.base is None # .reshape() creates a view

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
z = y[[2, 1]]
z.base is None  # advanced indexing creates a copy

## Selecting specific rows & columns

When using fancy indexing, the shape of the result reflects the shape of the *index arrays* rather than the shape of the *array being indexed*:

In [16]:
matrix = np.arange(1, 17).reshape(4, 4)
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [17]:
# Select rows 0 and 2, columns 1 and 3
print(matrix[[0, 2], [1, 3]])   # → elements (0,1) and (2,3)

[ 2 12]


In [18]:
x = np.random.randint(100, size=10)
ind = np.array([[3, 7],
                [4, 5]])
x[ind]

array([[31, 87],
       [61, 78]])

Fancy indexing also works in multiple dimensions. Consider the following array:

In [19]:
X = np.arange(12).reshape((3, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Like with standard indexing, the first index refers to the row, and the second to the column:

In [20]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
X[row, col]

array([ 2,  5, 11])

In [21]:
row.shape, col.shape

((3,), (3,))

In [ ]:
row[:, np.newaxis],col   #Column Vector (3, 1)

Notice that the first value in the result is ``X[0, 2]``, the second is ``X[1, 1]``, and the third is ``X[2, 3]``.
The pairing of indices in fancy indexing follows all the broadcasting rules that were mentioned in Broadcasting.
So, for example, if we combine a column vector and a row vector within the indices, we get a two-dimensional result:

In [22]:
X[row[:, np.newaxis], col]

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

Here, each row value is matched with each column vector, exactly as we saw in broadcasting of arithmetic operations.
For example:

## Combined Indexing

For even more powerful operations, fancy indexing can be combined with the other indexing schemes we've seen:

In [23]:
print(X)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


We can combine fancy and simple indices:

In [24]:
X[2, [2, 0, 1]]

array([10,  8,  9])

We can also combine fancy indexing with slicing:

In [25]:
print(X)
X[1:, [0]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[4],
       [8]])

In [26]:
X[1:, [2, 0, 1]]

array([[ 6,  4,  5],
       [10,  8,  9]])

And we can combine fancy indexing with masking:

In [ ]:
mask = np.array([1, 0, 1, 0])
mask

In [ ]:
row[:, np.newaxis], mask

In [ ]:
X[row[:, np.newaxis], mask]

All of these indexing options combined lead to a very flexible set of operations for accessing and modifying array values.

## Modifying Values with Fancy Indexing

Just as fancy indexing can be used to access parts of an array, it can also be used to modify parts of an array.
For example, imagine we have an array of indices and we'd like to set the corresponding items in an array to some value:

In [27]:
arr = np.arange(10)
arr[[2, 4, 6]] = -1
print(arr)  

[ 0  1 -1  3 -1  5 -1  7  8  9]


In [28]:
x = np.arange(10)
i = np.array([2, 1, 8, 4])
x[i] = 99
print(x)

[ 0 99 99  3 99  5  6  7 99  9]


We can use any assignment-type operator for this. For example:

In [29]:
x[i] -= 10
print(x)

[ 0 89 89  3 89  5  6  7 89  9]


In [30]:
a = 2, 3, 4
print(a)
a = (2, 3, 4)
print(a)

(2, 3, 4)
(2, 3, 4)


Notice, though, that repeated indices with these operations can cause some potentially unexpected results. Consider the following:

In [31]:
x = np.zeros(10)
x[[0, 0, 0]] = [4, 6, 8]
print(x)

[8. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Where did the 4 go? The result of this operation is to first assign ``x[0] = 4``, followed by ``x[0] = 6``.
The result, of course, is that ``x[0]`` contains the value 8.

Fair enough, but consider this operation:

In [32]:
i = [0,2, 3, 3, 4, 4, 4]
x[i] += 1
x

array([9., 0., 1., 1., 1., 0., 0., 0., 0., 0.])

In [33]:
A = np.ones(10)
A

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [34]:
ind = [3,3,5 ,5,5]
A[ind] += 2 
A

array([1., 1., 1., 3., 1., 3., 1., 1., 1., 1.])

You might expect that ``x[3]`` would contain the value 2, and ``x[4]`` would contain the value 3, as this is how many times each index is repeated. Why is this not the case?
Conceptually, this is because ``x[i] += 1`` is meant as a shorthand of ``x[i] = x[i] + 1``. ``x[i] + 1`` is evaluated, and then the result is assigned to the indices in x.
With this in mind, it is not the augmentation that happens multiple times, but the assignment, which leads to the rather nonintuitive results.

So what if you want the other behavior where the operation is repeated? For this, you can use the ``at()`` method of ufuncs (available since NumPy 1.8), and do the following:

In [35]:
x = np.zeros(10)
i = [2, 3, 3, 4, 4, 4]
np.add.at(x, i, 2)
print(x)

[0. 0. 2. 4. 6. 0. 0. 0. 0. 0.]


In [ ]:
a = np.array([1, 2, 3, 4])
np.add.at(a, [0, 1, 2, 2, 2], 1)
a

The ``at()`` method does an in-place application of the given operator at the specified indices (here, ``i``) with the specified value (here, 1).
Another method that is similar in spirit is the ``reduceat()`` method of ufuncs, which you can read about in the NumPy documentation.

In [ ]:
np.negative.at(a, [0, 1]) #Set items 0 and 1 to their negative values
a

## Example: Binning Data

You can use these ideas to efficiently bin data to create a histogram by hand.
For example, imagine we have 100 values and would like to quickly find where they fall within an array of bins.
We could compute it using ``ufunc.at`` like this:

In [ ]:
np.random.seed(42)
x = np.random.randint(100, size=20)
x

In [ ]:
# compute a histogram by hand
bins = np.linspace(1, 99, 5)
print(bins)

In [ ]:
# find the appropriate bin for each x
i = np.searchsorted(bins, x)
i

In [ ]:
# add 1 to each of these bins
counts = np.zeros_like(bins)
counts

In [ ]:
np.add.at(counts, i, 1)
counts

The counts now reflect the number of points within each bin–in other words, a histogram:

In [ ]:
import matplotlib.pyplot as plt
# plot the results
plt.plot(bins, counts, linestyle='dotted');

In [ ]:
plt.hist(x, bins, histtype='step');

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn; seaborn.set()  # set plot styles
plt.hist(x, bins);

Of course, it would be silly to have to do this each time you want to plot a histogram.
This is why Matplotlib provides the ``plt.hist()`` routine, which does the same in a single line:

```python
plt.hist(x, bins, histtype='step');
```

In [ ]:
plt.hist(x, bins, histtype='step');